version: "3.11"

services:
  web:
    build: .
    ports: 
      - "5000:5000"
    volumes: 
      - .:/project
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  localhost:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0880
      POSTGRES_DB: test_task
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
